### ISSUE TITLE
Reintroduce notifications about parking

### ISSUE THREAD

**Issue by henrinormak** [Pargi/Pargi-iOS#11]
Currently, the app does not notify users of ongoing parking, this was a nice feature of the old version that should be reintroduced in some clever way.

The old approach was very manual, it had a few buttons and a settings option that controlled it, but nothing else, this wasn't particularly good (default values should be so good that you wouldn't need to fiddle with buttons).

*Requirements*
- Add back the time based notifications, with time interval at 1h and going up to 4h
- Add a geofence based notification, with the distance at 1km
- Both of these should be enabled by default. The geofence should be smart enough not to active if the user disallowed background location usage for the app.

**Comment by margusholland** [comment]
Updating location in the background would be very handy. To save battery life, lets only listen to significant changes in location – e.g. you most probably park your car pretty close to the place you’re going to. And if you start driving and the location changes quite significantly, it’s probably safe to presume the need to end parking. Time based notifications are of course a plus, but as a ”daily user” of old Pargi version, I can say that I very rarely actually used it. Maybe because of the uncertain state of the UI for those buttons – never really figured out which ones are ”on” and which ones ”off”.

**Comment by henrinormak** [comment]
Heh, I agree that the old UI was confusing, we could in theory use geofencing (no need to track location ourselves, just set up a perimeter around the point of parking)

I will investigate this and create an issue.

**Comment by henrinormak** [comment]
I updated the issue, let's include a geofence based notification as well, however, only do that if the user allowed background location updates.
